_format_version: "3.0"

services:
  - name: simulation-engine
    url: http://simulation-engine:8001
    routes:
      - name: sim-core
        paths:
          - /api/v1/sessions
          - /api/v1/stories
          - /api/v1/steps
          - /api/v1/aas
          - /api/v1/aasx
          - /api/v1/progress
        strip_path: false
      - name: sim-health
        paths:
          - /api/v1/health
          - /api/v1/health/simulation
        strip_path: false
  - name: compliance-service
    url: http://compliance-service:8002
    routes:
      - name: compliance
        paths:
          - /api/v1/compliance
          - /api/v1/rules
          - /api/v1/reports
        strip_path: false
      - name: compliance-health
        paths:
          - /api/v1/health/compliance
        strip_path: false
  - name: gamification-service
    url: http://gamification-service:8003
    routes:
      - name: gamification
        paths:
          - /api/v1/points
          - /api/v1/achievements
          - /api/v1/leaderboard
          - /api/v1/streaks
        strip_path: false
      - name: gamification-health
        paths:
          - /api/v1/health/gamification
        strip_path: false
  - name: edc-simulator
    url: http://edc-simulator:8004
    routes:
      - name: edc
        paths:
          - /api/v1/edc
        strip_path: false
      - name: edc-health
        paths:
          - /api/v1/health/edc
        strip_path: false
  - name: collaboration-service
    url: http://collaboration-service:8005
    routes:
      - name: collaboration
        paths:
          - /api/v1/annotations
          - /api/v1/gap_reports
          - /api/v1/votes
          - /api/v1/comments
        strip_path: false
      - name: collaboration-health
        paths:
          - /api/v1/health/collaboration
        strip_path: false

consumers:
  - username: keycloak
    jwt_secrets:
      - key: http://localhost:8080/realms/dpp
        algorithm: RS256
        rsa_public_key: |
          -----BEGIN PUBLIC KEY-----
          REPLACE_WITH_KEYCLOAK_REALM_PUBLIC_KEY
          -----END PUBLIC KEY-----
__ANON_CONSUMER__

plugins:
  - name: cors
    config:
      origins: __CORS_ORIGINS__
      methods: ["GET", "POST", "PATCH", "DELETE", "OPTIONS"]
      headers: ["Authorization", "Content-Type", "X-Dev-User", "X-Dev-Roles"]
  - name: rate-limiting
    config:
      minute: 100
      policy: local
  - name: jwt
    config:
      key_claim_name: iss
      claims_to_verify:
        - exp
      run_on_preflight: false
__ANON_CONFIG__
