stateDiagram-v2
  [*] --> INITIAL
  INITIAL --> REQUESTING
  REQUESTING --> REQUESTED
  REQUESTED --> OFFERED
  OFFERED --> ACCEPTED
  ACCEPTED --> AGREED
  AGREED --> VERIFIED
  VERIFIED --> FINALIZED
  OFFERED --> TERMINATED
  REQUESTED --> TERMINATED
