openapi: 3.1.0
info:
  title: Compliance Service
  version: 0.1.0
paths:
  /api/v1/health:
    get:
      summary: Health
      operationId: health_api_v1_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/v1/health/{service_name}:
    get:
      summary: Health Named
      operationId: health_named_api_v1_health__service_name__get
      parameters:
      - name: service_name
        in: path
        required: true
        schema:
          type: string
          title: Service Name
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/compliance/check:
    post:
      summary: Check
      operationId: check_api_v1_compliance_check_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComplianceCheckRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/rules:
    get:
      summary: List Rules
      operationId: list_rules_api_v1_rules_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/v1/reports:
    get:
      summary: List Reports
      operationId: list_reports_api_v1_reports_get
      parameters:
      - name: session_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Session Id
      - name: story_code
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Story Code
      - name: status
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Status
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 50
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/reports/{report_id}:
    get:
      summary: Get Report
      operationId: get_report_api_v1_reports__report_id__get
      parameters:
      - name: report_id
        in: path
        required: true
        schema:
          type: string
          title: Report Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ComplianceCheckRequest:
      properties:
        data:
          type: object
          title: Data
        regulations:
          items:
            type: string
          type: array
          title: Regulations
        user_id:
          anyOf:
          - type: string
          - type: 'null'
          title: User Id
        session_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Session Id
        story_code:
          anyOf:
          - type: string
          - type: 'null'
          title: Story Code
      type: object
      required:
      - data
      - regulations
      title: ComplianceCheckRequest
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
