openapi: 3.1.0
info:
  title: Platform Core
  version: 0.2.0
paths:
  /api/v2/health:
    get:
      summary: Health
      operationId: health_api_v2_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/v2/health/platform-core:
    get:
      summary: Service Health
      operationId: service_health_api_v2_health_platform_core_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/v2/core/simulation/status:
    get:
      summary: Simulation Status
      operationId: simulation_status_api_v2_core_simulation_status_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/v2/core/compliance/status:
    get:
      summary: Compliance Status
      operationId: compliance_status_api_v2_core_compliance_status_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/v2/core/gamification/status:
    get:
      summary: Gamification Status
      operationId: gamification_status_api_v2_core_gamification_status_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/v2/core/collaboration/status:
    get:
      summary: Collaboration Status
      operationId: collaboration_status_api_v2_core_collaboration_status_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
